# @package _global_

environment:
  id: Gym-Grid/Gridworld-Snake-6x6-v0

experiment:
  training_steps: 300000
  testing_episodes: 100
  testing_points: 3000

monitor:
  button_cell_id: 31
  button_flip_act: 1
  forbidden_states:
    - 2
    - 8
#    - 14
    - 20
    - 26
    - 32