# @package _global_

environment:
  id: Gym-Grid/Gridworld-Bottleneck

experiment:
  training_steps: 35000
  testing_episodes: 100
  testing_points: 350

monitor:
  button_cell_id: 31
  button_flip_act: 1
  forbidden_states:
    - 2
    - 8
#    - 14
    - 20
    - 26
    - 32