# @package _global_

environment:
  id: Gym-Grid/Gridworld-Empty-Distract-6x6-v0

experiment:
  training_steps: 20000
  testing_episodes: 1
  testing_points: 200

monitor:
  button_cell_id: 31
  button_flip_act: 1
  forbidden_states:
    - 2
    - 8
#    - 14
    - 20
    - 26
    - 32