# @package _global_

environment:
  id: Gym-Grid/Gridworld-Penalty-3x3-v0

experiment:
  training_steps: 20000
  testing_points: 200
  testing_episodes: 100

monitor:
  button_cell_id: 0
  button_flip_act: 0
  forbidden_states:
    - 1
    - 4