# @package _global_

environment:
  id: Gym-Grid/RiverSwim-6-v0

experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_points: 200

agent:
  critic:
    lr:
      init_value: 0.5
      min_value: 0.05
    lr_visit:
      init_value: 0.5
      min_value: 0.05

monitor:
  button_cell_id: 0
  button_flip_act: 0
  forbidden_states: