# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: river_swim
  monitor: n_expert
  experiment.datadir: data
  experiment.hide_progress_bar: True
  experiment.rng_seed: range(0, 30)
  agent: optimistic_init
  algorithm: q_visit
