# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: river_swim, medium_distract, quicksand_distract, corridor
  monitor: full, random_nonzero, binary_stateless, n, level, button
  experiment.datadir: data
  experiment.hide_progress_bar: True
  experiment.rng_seed: range(0, 30)
  agent: optimistic_init #, pessimistic_init
  algorithm: q_visit
