# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: river_swim
  monitor: button, binary_stateless
  experiment.datadir: data
  experiment.hide_progress_bar: True
  experiment.rng_seed: range(0, 2)
  agent: optimistic_init
  agent.critic.q0_max: -100, 55
  agent.critic.r0_max: 0, 1
  algorithm: q_visit
  monitor.prob: 1, 0.1
