# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: distract, two_room
  monitor: n_expert, ask, button, n_supporter, level, random
  experiment.datadir: data
  experiment.hide_progress_bar: True
  experiment.rng_seed: range(0, 30)
  monitor.prob: 0.8, 0.2, 0.05