# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: corridor, two_room_3x5
  monitor: full, random_nonzero, ask, button, n, level
  experiment.datadir: data
  experiment.hide_progress_bar: True
  experiment.rng_seed: range(20, 30)
  agent: optimistic_init
  algorithm: q_visit
