# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: bypass
  monitor: ask, button, n_supporter, level, random_nonzero, full
  experiment.datadir: data
  experiment.hide_progress_bar: True
  experiment.rng_seed: range(0, 30)
