# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: bottleneck
  monitor: random, ask, button, n_supporter, n_expert, level
  experiment.datadir: ../Mon-MBIE-EB/data
  experiment.hide_progress_bar: True
  experiment.rng_seed: range(0, 30)
  monitor.prob: 1, 0.8, 0.2, 0.05
