# @package _global_
algorithm:
  id: q_visit

agent:
  critic:
    id: QTableCriticWithVisitQ

  actor:
    id: EpsilonGreedyWithVisitQ
    beta_bar: 0.01
    eps:
      init_value: 1.0
      min_value: 0.0
