# @package _global_
algorithm:
  id: ucb

agent:
  critic:
    id: QTableCritic
    q0_visit_min: 200
    q0_visit_max: 200

  actor:
    id: EpsilonGreedyWithUCB
    beta_bar: null
    eps:
      init_value: 1.0
      min_value: 0.0
