critic:
  id: QTableCritic
  q0_max: -10
  q0_visit_max: -1
  q0_visit_min: -1
  r0_max: 1
  gamma: 0.99
  gamma_visit: 0.9

  lr:
    id: LinearDecay
    init_value: 1.0
    min_value: 1.0
    decay: null
    steps: ${experiment.training_steps}
    warmup: 0

  lr_visit:
    id: LinearDecay
    init_value: 1.0
    min_value: 1.0
    decay: null
    steps: ${experiment.training_steps}
    warmup: 0

actor:
  id: EpsilonGreedy
  beta_bar: null

  eps:
    id: LinearDecay
    init_value: 1.0
    min_value: 0.0
    decay: null
    steps: ${experiment.training_steps}
    warmup: 0
